xrdb -merge "$XDG_CONFIG_HOME/X11/xresources"

# set workman keymap and map CAPS to BCKSPC
setxkbmap workman && xset r 66

# check for updates
~/bin/xbps-num-packages.sh &

# start DM programs
dunst &
picom &
slstatus &

# start daemons
gpg-agent --daemon
calcurse --daemon

~/bin/startup.sh &

exec dbus-launch --sh-syntax --exit-with-session dwm
