[flags]
rate = "1s"
left_legend = true
time_delta = 1000
hide_time = true
battery = true
disable_click = true
show_table_scroll_position = true
temperature_type = "celsius"

[styles.graphs]
graph_color = "dark gray"
legend_text = {color = "light blue"}

[styles.widgets]
border_color = "dark gray"
selected_border_color = "light blue"
widget_title = {color = "gray"}
text = {color = "gray"}
selected_text = {color = "black", bg_color = "light blue"}
disabled_text = {color = "dark gray"}

[[row]]
  ratio=20
  [[row.child]]
  type="cpu"
[[row]]
    ratio=20
    [[row.child]]
      ratio=2
      type="net"
  [[row.child]]
      ratio=3
      type="mem"
[[row]]
  ratio=60
  [[row.child]]
    ratio=2
    [[row.child.child]]
      ratio=2
      type="temp"
    [[row.child.child]]
      type="disk"
    [[row.child.child]]
      type="battery"
  [[row.child]]
    ratio=3
    type="proc"
    default=true
