[flags]
rate = 1000
left_legend = true
time_delta = 1000
hide_time = true
battery = true
disable_click = true
color = "nord"
show_table_scroll_position = true

[colors]
table_header_color="LightGreen"
widget_title_color="LightBlue"
avg_cpu_color="Red"
cpu_core_colors=["LightMagenta", "LightYellow", "LightCyan", "LightGreen", "LightBlue", "LightRed", "Cyan", "Green", "Blue", "Red"]
ram_color="LightBlue"
swap_color="#D08770"
rx_color="LightBlue"
tx_color="#D08770"
border_color="DarkGray"
highlighted_border_color="LightBlue"
text_color="Gray"
selected_text_color="Black"
selected_bg_color="LightBlue"
graph_color="#616E88"
high_battery_color="Green"
medium_battery_color="Yellow"
low_battery_color="Red"

[[row]]
  ratio=20
  [[row.child]]
  type="cpu"
[[row]]
    ratio=20
    [[row.child]]
      ratio=2
      type="net"
  [[row.child]]
      ratio=3
      type="mem"
[[row]]
  ratio=60
  [[row.child]]
    ratio=2
    [[row.child.child]]
      ratio=2
      type="temp"
    [[row.child.child]]
      type="disk"
    [[row.child.child]]
      type="battery"
  [[row.child]]
    ratio=3
    type="proc"
    default=true
